### ISSUE TITLE
Kube Token no longer auto retrieving certs for oidc integrated clusters

### ISSUE THREAD

**Issue by mlbiam** [TremoloSecurity/OpenUnison#888]
surfaced by https://github.com/OpenUnison/openunison-k8s/issues/109 when you get the following error:

`Unable to connect to the server: tls: failed to verify certificate: x509: “kube-apiserver” certificate is not trusted`

This started in 1.0.40.  The workaround is to downgrade to 1.0.39 or add the base64 encoded certificate to your values.yaml:

```yaml
trusted_certs:
- name: k8s-master
  pem_b64: base64 encoded certificate
```
