### ISSUE TITLE
Problem using generated kubeconfig after oulogin

### ISSUE THREAD

**Issue by mojochao** [TremoloSecurity/OpenUnison#966]
I am trying to use OpenUnison with Okta for SSO authentication, but I am facing issues when trying to use the generated kubeconfig after a successful login.

```
$ kubectl oulogin --host k8sou.apps.some.hostname.example.com
oulogin 0.0.7
Checking for existing issuer https://k8sou.apps.some.hostname.example.com/auth/idp/k8sIdp
Invalid context or does not exist, launching browser to login
Starting OpenID Connect for host k8sou.apps.some.hostname.example.com
kubectl configuration created

$ kubectl cluster-info
E0512 13:30:22.875033   89616 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server has asked for the client to provide credentials"
E0512 13:30:22.952779   89616 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server has asked for the client to provide credentials"
E0512 13:30:23.035756   89616 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server has asked for the client to provide credentials"
error: You must be logged in to the server (Unauthorized)

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

Latest OpenUnison was installed into a self-managed Kubernetes cluster using `ouctl`:

The ingress controller used is ingress-nginx with Let's Encrypt for TLS certificates, and certificates were correctly created.

I followed the OpenUnison documentation, configuring the following in my `orchestra.values.yaml` file, modified from the example downloaded 
 as documented:

- configured enable_impersonation: false
- configured oidc config section to use Okta OIDC app created for OpenUnison SSO integration
- configured trusted_certs with `ca.crt` from control plane node
 
I also configured the Okta app client secret in `client-secret.txt`

```shell
$ ouctl install-auth-portal -s client-secret.txt orchestra.values.yaml
```

The installation process completed successfully, and I was able to log in to the OpenUnison portal using Okta credentials.
However, when I try to use the generated kubeconfig file, I encounter the "Unauthorized" error shown earlier.

I have checked that the kubeconfig file is correctly generated and contains the necessary information:

- clusters.0.cluster.certificate-authority-data contains the base64-encoded CA certificate from `ca.crt` of the control plane node
- users.0.user.auth-provider.config.id-token contains correct data from Okta in the base64-encoded JWT
- users.0.user.auth-provider.config.idp-certificate-authority-data contains a base64-encoded certificate but I'm not sure of its provenance

I have looked through the logs but found nothing suspicious, to my eyes at least. How can I troubleshoot this issue further? Are there any specific steps I might have missed in the OpenUnison setup? I can provide additional details of config if helpful.

Many thanks in advance.

**Comment by mlbiam** [comment]
> E0512 13:30:23.035756   89616 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: the server has asked for the client to provide credentials"

This usually means the cluster hasn't been setup for OpenID Connect.  Are you using impersonation or direct integration?  Does the dashboard work?  What kind of cluster and where is it hosted?

**Comment by mojochao** [comment]
The cluster is a self-hosted cluster (v1.28) built with Kubespray on Proxmox-managed VMs in a data center available once connected to an internal VPN. Its nodes are running:

```
infra@control-plane-01:~$ uname -a
Linux control-plane-01 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
```

The API server is running:

```
kube-apiserver \
--advertise-address=10.11.9.11 \
--allow-privileged=true \
--anonymous-auth=True \
--apiserver-count=3 \
--authorization-mode=Node,RBAC \
--bind-address=0.0.0.0 \
--client-ca-file=/etc/kubernetes/ssl/ca.crt \
--default-not-ready-toleration-seconds=300 \
--default-unreachable-toleration-seconds=300 \
--enable-admission-plugins=NodeRestriction \
--enable-aggregator-routing=False \
--enable-bootstrap-token-auth=true \
--endpoint-reconciler-type=lease \
--etcd-cafile=/etc/ssl/etcd/ssl/ca.pem \
--etcd-certfile=/etc/ssl/etcd/ssl/node-control-plane-01.pem \
--etcd-keyfile=/etc/ssl/etcd/ssl/node-control-plane-01-key.pem \
--etcd-servers=https://10.11.9.11:2379,https://10.11.9.12:2379,https://10.11.9.13:2379 \
--event-ttl=1h0m0s \
--kubelet-client-certificate=/etc/kubernetes/ssl/apiserver-kubelet-client.crt \
--kubelet-client-key=/etc/kubernetes/ssl/apiserver-kubelet-client.key \
--kubelet-preferred-address-types=InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP \
--profiling=False \
--proxy-client-cert-file=/etc/kubernetes/ssl/front-proxy-client.crt \
--proxy-client-key-file=/etc/kubernetes/ssl/front-proxy-client.key \
--request-timeout=1m0s \
--requestheader-allowed-names=front-proxy-client \
--requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.crt \
--requestheader-extra-headers-prefix=X-Remote-Extra- \
--requestheader-group-headers=X-Remote-Group \
--requestheader-username-headers=X-Remote-User \
--secure-port=6443 \
--service-account-issuer=https://kubernetes.default.svc.cluster.local \
--service-account-key-file=/etc/kubernetes/ssl/sa.pub \
--service-account-lookup=True \
--service-account-signing-key-file=/etc/kubernetes/ssl/sa.key \
--service-cluster-ip-range=10.233.0.0/18 \
--service-node-port-range=30000-32767 \
--storage-backend=etcd3 \
--tls-cert-file=/etc/kubernetes/ssl/apiserver.crt \
--tls-private-key-file=/etc/kubernetes/ssl/apiserver.key
```

I read some things that seemed to indicate that the apiserver needed some `--oidc-*` flags added:

```
--oidc-issuer-url=https://k8sou.apps.las.cap.mysamba.tv/auth/idp/k8sIdp
--oidc-client-id=kubernetes
--oidc-username-claim=sub
--oidc-groups-claim=groups
--oidc-ca-file=/etc/kubernetes/pki/openunison-ca.pem
```

I had this previously working with an earlier version of OpenUnison earlier this year without changes to the apiserver command line, however, so I'm not sure if this is the problem.

My OIDC config in my `orchestra.values.yaml` file contains:

```
oidc:
  client_id: 0oag300lz8YpljtDY697
  issuer: https://sambatv.okta.com/
  user_in_idtoken: false
  domain: ""
  scopes: openid email profile groups
  claims:
    sub: email
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups
```

My generated kubeconfig `clusters.0.cluster.certificate-authority-data` contains the data from my `/etc/kubernetes/ssl/ca.crt` file, which was used to configure `trusted_certs.k8s_master`:

```
infra@control-plane-01:~$ cat /etc/kubernetes/ssl/ca.crt
-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIIcAw/PmUfl34wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
AxMKa3ViZXJuZXRlczAeFw0yNDAyMDIxMjIxMzhaFw0zNDAxMzAxMjI2MzhaMBUx
EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC91jnxjH7RMxCzL1kFc3PL7FZaAnzI9qMaLIoZ9obmjijkJJKXNecfUs/W
diEyNdx+qzpo6qC2MrYsZ8pJQSIwddcgqVoEGAjWLC/2nI11o3/32GYqvhkmoWgp
qHuj/dkGA3kaHaJU46D6a+DeDWFV9GRPlQP6/TBWObU7ZPpOd6BKY47EczSNg3VI
mgC8TdiLXwSZ9mOCGxmAKGpw6lfbJuqQP0MMmtfNwIve8ymqrCby7CdfNK5LCRsQ
7d5wAMIJwYq/yimN4scnD79KI+UWlzOcdOwy2A9E7SM1bqcngfE5geWFqxUkWYfv
LSH5D2wBqs7+FDTRP42ScTx5PueXAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS33RnN/eSNITb+od+t+taSczNSyzAV
BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB5kJRRB320
dBAUp+41KfatimkZHk/sMHBoDQbtAfqLCGbdKt0fvkGZ3FtJWoyMgAQZkuyFYenZ
h6ujQyXZ7qO43gwFBgBpJ887g1Nb0HG2Gmp15akDxUohsobMsOdMu09O6Bg4TxVX
8ANyeHsXjx3nCp+mCZ19q6Vhqbyy0BkUpWy0dDFdasaNQafRzNQtqlErB5d02RS9
t+R+LWKwCJ7gXAaUCe0s2nnrPLHiJSbAgRc8vYev9A4eFZ2sfS6c6sofsx0KTmiC
Xoa/CovrnXWC7dK7E8XO9qoxXCO3L0ZptmExd5F6t8ORrT9q96jeRwlbli4KUVly
dwqG/Hv9dWou
```

Or as base64 encoded:

```
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY0F3L1BtVWZsMzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1ESXhNakl4TXpoYUZ3MHpOREF4TXpBeE1qSTJNemhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM5MWpueGpIN1JNeEN6TDFrRmMzUEw3RlphQW56STlxTWFMSW9aOW9ibWppamtKSktYTmVjZlVzL1cKZGlFeU5keCtxenBvNnFDMk1yWXNaOHBKUVNJd2RkY2dxVm9FR0FqV0xDLzJuSTExbzMvMzJHWXF2aGttb1dncApxSHVqL2RrR0Eza2FIYUpVNDZENmErRGVEV0ZWOUdSUGxRUDYvVEJXT2JVN1pQcE9kNkJLWTQ3RWN6U05nM1ZJCm1nQzhUZGlMWHdTWjltT0NHeG1BS0dwdzZsZmJKdXFRUDBNTW10Zk53SXZlOHltcXJDYnk3Q2RmTks1TENSc1EKN2Q1d0FNSUp3WXEveWltTjRzY25ENzlLSStVV2x6T2NkT3d5MkE5RTdTTTFicWNuZ2ZFNWdlV0ZxeFVrV1lmdgpMU0g1RDJ3QnFzNytGRFRSUDQyU2NUeDVQdWVYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTMzNSbk4vZVNOSVRiK29kK3QrdGFTY3pOU3l6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVrSlJSQjMyMApkQkFVcCs0MUtmYXRpbWtaSGsvc01IQm9EUWJ0QWZxTENHYmRLdDBmdmtHWjNGdEpXb3lNZ0FRWmt1eUZZZW5aCmg2dWpReVhaN3FPNDNnd0ZCZ0JwSjg4N2cxTmIwSEcyR21wMTVha0R4VW9oc29iTXNPZE11MDlPNkJnNFR4VlgKOEFOeWVIc1hqeDNuQ3ArbUNaMTlxNlZocWJ5eTBCa1VwV3kwZERGZGFzYU5RYWZSek5RdHFsRXJCNWQwMlJTOQp0K1IrTFdLd0NKN2dYQWFVQ2UwczJubnJQTEhpSlNiQWdSYzh2WWV2OUE0ZUZaMnNmUzZjNnNvZnN4MEtUbWlDClhvYS9Db3ZyblhXQzdkSzdFOFhPOXFveFhDTzNMMFpwdG1FeGQ1RjZ0OE9SclQ5cTk2amVSd2xibGk0S1VWbHkKZHdxRy9IdjlkV291Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
```

Also in my generated kubeconfig is the following value for `users.0.user.auth-provider.config.idp-certificate-data`:

```
-----BEGIN CERTIFICATE-----
MIIFQDCCBCigAwIBAgISBcvbhghDLRN1JlbDWlZBUTDAMA0GCSqGSIb3DQEBCwUA
MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
EwNSMTEwHhcNMjUwNTA3MTkxOTU0WhcNMjUwODA1MTkxOTUzWjAsMSowKAYDVQQD
EyFrOHNvdS5hcHBzLnN0Zy5sYXMuY2FwLm15c2FtYmEudHYwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCVAqMTAPl1zCfbnfknlPoUmhUZrnEcrTGnGbsP
/Ut9IVaNgyLBuYEaFLLifj+3dMef5Llf0R7aF8UKHk4IG6QAIEgSPPbjQ+3cpwkX
v1bh7YYxfGG42J4xpf5p6WoLB8oMxjYb+cp1hKV6nn2RV6AtvypBkcnglsjNC1Zm
7rULGk2eybKcJYUNS/40/WfTmcAT/S3pSJpVW+r3qD77nM9b3siXCRnAlNJ9mPpz
IMlMk8lpvfdhQz7mgMUHmsyyv1B/8K0TSkZLBp5iSQtki053VTYpYCRW0FVbASiy
1r/rYO08EqkLEugFmqRNMmWHv5/OWKZtR1xX76fKMbX/DYVpAgMBAAGjggJTMIIC
TzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFMgu0eOlrc2qy1rNfn6o8G6Y5D/AMB8G
A1UdIwQYMBaAFMXPRqTq9MPAemyVxC2wXpIvJuO5MDMGCCsGAQUFBwEBBCcwJTAj
BggrBgEFBQcwAoYXaHR0cDovL3IxMS5pLmxlbmNyLm9yZy8wTwYDVR0RBEgwRoIh
azhzZGIuYXBwcy5zdGcubGFzLmNhcC5teXNhbWJhLnR2giFrOHNvdS5hcHBzLnN0
Zy5sYXMuY2FwLm15c2FtYmEudHYwEwYDVR0gBAwwCjAIBgZngQwBAgEwLgYDVR0f
BCcwJTAjoCGgH4YdaHR0cDovL3IxMS5jLmxlbmNyLm9yZy82NS5jcmwwggEDBgor
BgEEAdZ5AgQCBIH0BIHxAO8AdgDM+w9qhXEJZf6Vm1PO6bJ8IumFXA2XjbapflTA
/kwNsAAAAZasZkKDAAAEAwBHMEUCIQD9Tai9txiQtpf21/SVqeBVkCU+EBtY5iFB
ft4wXgjm2QIgPzglIYibxa91cPC7z9WqCDsPmNdk9mkq77jyWViqYhkAdQAaBP9J
0FQdQK/2oMO/8djEZy9O7O4jQGiYaxdALtyJfQAAAZasZkPyAAAEAwBGMEQCIGM7
15MMp7Xt2NFsqoTXEi8ftfKY+e6WIaj6TKWqn9UtAiB1pygbM4RJxzBFNbWORsap
zbvSULtl81yFcmCYSJd+GzANBgkqhkiG9w0BAQsFAAOCAQEAUUosKLIu+81c0XZw
xTDnR+JfkgbBRj60cJ2DK/EWhrpOtAaQlCTDdx5VCc3X68d0jDeVF9J6+7AFbaX4
wsha1CP1MM8sbth/O1jw2jmghpf5Q+3QS4PTY5601uM+g7n/N4AVX9i9IdnK6fQP
Ju6FWVTZ3goq5i4ZMO+tbQmG6dYhFfegdmwrlDb3E+LjoxzD4LE0JqCb9wj/UCd1
ilM2w/NRNOF6/BRiRkJnReoihpLYzTKOoR3312N7+S2UyNil75bd+lFWTz4nUMV6
pQDluR6NF3PkwurDqCnfzDHEOABUoiR3jfAtNP+kfMHQ832vJyrrRvRbxM3v1sb/
QTGyhQ==
-----END CERTIFICATE-----
```

What is the source of this certificate?

I've installed the kubernete-dashboard, but don't see any links to it on the OpenUnison web page upon successful SSO w/ Okta.  For reference, here's my `orchestra.values.yaml` file:

```
network:
  openunison_host: "k8sou.apps.stg.las.cap.mysamba.tv"
  dashboard_host: "k8sdb.apps.stg.las.cap.mysamba.tv"
  api_server_host: "k8sapi.apps.stg.las.cap.mysamba.tv"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://10.11.9.11:6443
  force_redirect_to_tls: false
  createIngressCertificate: true
  ingress_type: nginx
  ingress_annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: k8sou.apps.stg.las.cap.mysamba.tv,k8sdb.apps.stg.las.cap.mysamba.tv,k8sapi.apps.stg.las.cap.mysamba.tv
    kubernetes.io/ingress.class: nginx-external

cert_template:
  ou: SambaTV
  o: Infrastructure
  l: cap-staging-las
  st: NV
  c: USA

myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: cap-staging-las
enable_impersonation: false

impersonation:
  use_jetstack: true
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  require_session: true
  new: true

certs:
  use_k8s_cm: false

trusted_certs:
- name: k8s_master
  pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY0F3L1BtVWZsMzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeU1ESXhNakl4TXpoYUZ3MHpOREF4TXpBeE1qSTJNemhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM5MWpueGpIN1JNeEN6TDFrRmMzUEw3RlphQW56STlxTWFMSW9aOW9ibWppamtKSktYTmVjZlVzL1cKZGlFeU5keCtxenBvNnFDMk1yWXNaOHBKUVNJd2RkY2dxVm9FR0FqV0xDLzJuSTExbzMvMzJHWXF2aGttb1dncApxSHVqL2RrR0Eza2FIYUpVNDZENmErRGVEV0ZWOUdSUGxRUDYvVEJXT2JVN1pQcE9kNkJLWTQ3RWN6U05nM1ZJCm1nQzhUZGlMWHdTWjltT0NHeG1BS0dwdzZsZmJKdXFRUDBNTW10Zk53SXZlOHltcXJDYnk3Q2RmTks1TENSc1EKN2Q1d0FNSUp3WXEveWltTjRzY25ENzlLSStVV2x6T2NkT3d5MkE5RTdTTTFicWNuZ2ZFNWdlV0ZxeFVrV1lmdgpMU0g1RDJ3QnFzNytGRFRSUDQyU2NUeDVQdWVYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTMzNSbk4vZVNOSVRiK29kK3QrdGFTY3pOU3l6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjVrSlJSQjMyMApkQkFVcCs0MUtmYXRpbWtaSGsvc01IQm9EUWJ0QWZxTENHYmRLdDBmdmtHWjNGdEpXb3lNZ0FRWmt1eUZZZW5aCmg2dWpReVhaN3FPNDNnd0ZCZ0JwSjg4N2cxTmIwSEcyR21wMTVha0R4VW9oc29iTXNPZE11MDlPNkJnNFR4VlgKOEFOeWVIc1hqeDNuQ3ArbUNaMTlxNlZocWJ5eTBCa1VwV3kwZERGZGFzYU5RYWZSek5RdHFsRXJCNWQwMlJTOQp0K1IrTFdLd0NKN2dYQWFVQ2UwczJubnJQTEhpSlNiQWdSYzh2WWV2OUE0ZUZaMnNmUzZjNnNvZnN4MEtUbWlDClhvYS9Db3ZyblhXQzdkSzdFOFhPOXFveFhDTzNMMFpwdG1FeGQ1RjZ0OE9SclQ5cTk2amVSd2xibGk0S1VWbHkKZHdxRy9IdjlkV291Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

monitoring:
  prometheus_service_account: system:serviceaccount:prometheus:prometheus-kube-prometheus-prometheus

oidc:
  client_id: 0oag300lz8YpljtDY697
  issuer: https://sambatv.okta.com/
  user_in_idtoken: false
  domain: ""
  scopes: openid email profile groups
  claims:
    sub: email
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:prometheus:prometheus-kube-prometheus-prometheus
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  enable_provisioning: false
  use_standard_jit_workflow: true
```
